[WIP] Upgrading rds-broker and ginkgo
alphagov/paas-rds-metric-collector pull request #38
Opened 2023-10-27 14:39 UTC by fearoffish

Working on upgrades to all the things

2023-11-16 11:44 UTC, corlettb requested changes
remove a couple of comments and I think we are good to go.

2023-11-16 11:44 UTC, corlettb commented on main_test.go
> +		//var err error
Remove comment

2023-11-16 11:44 UTC, corlettb commented on suite_test.go
> +	// "fmt"
remove comment

2023-11-21 07:38 UTC, malcgds commented on main_test.go
> +		//var err error
Done

2023-11-21 07:38 UTC, malcgds commented on suite_test.go
> +	// "fmt"
Done

2023-11-21 08:39 UTC, corlettb approved these changes

2023-11-21 08:50 UTC, merged